[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#f05ba9"
backgroundColor = "#dfe3e8"
secondaryBackgroundColor = "#fbfbfc"
textColor = "#171717"
font = "sans serif"
